server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yjmming
mybatis:
  type-aliases-package: top.westyle.manager.entity
#连接池配置信息
#spring