server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/manager?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: yjmming
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  type-aliases-package: top.westyle.manager.entity
  #mapper-locations: classpath:mapping/*.xml